services:
  redis:
    image: redis:7.0.12
    ports:
      - "6379:6379"

  link_db:
    image: postgres:14.6-alpine
    container_name: link_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=link_shortener_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  link_shortener:
    image: link_shortener
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://link_db:5432/link_shortener_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

      SPRING_FLYWAY_ENABLED: "true"
      SPRING_FLYWAY_LOCATIONS: classpath:db/migration
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"

    depends_on:
      - redis
      - link_db
