CREATE TABLE links
(
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  short_link       VARCHAR(520)  NOT NULL,
  original_link    VARCHAR(3520)  NOT NULL,
  created_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  expired_at       TIMESTAMP WITHOUT TIME ZONE,
  CONSTRAINT links_pkey PRIMARY KEY (id)
);